<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Andrea Perez Pizarro">

<title>Linguistic Exclusion and Health Equity: Indigenous Language as a Barrier to Formal Healthcare in Mexico – andreappizarro</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">andreappizarro</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#theory-and-hypothesis" id="toc-theory-and-hypothesis" class="nav-link" data-scroll-target="#theory-and-hypothesis">Theory and Hypothesis</a></li>
  <li><a href="#research-design" id="toc-research-design" class="nav-link" data-scroll-target="#research-design">Research Design</a></li>
  <li><a href="#summary-statistics" id="toc-summary-statistics" class="nav-link" data-scroll-target="#summary-statistics">Summary Statistics</a>
  <ul class="collapse">
  <li><a href="#empirical-extension" id="toc-empirical-extension" class="nav-link" data-scroll-target="#empirical-extension">Empirical Extension</a></li>
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings">Findings</a></li>
  <li><a href="#discussion-and-policy-implications" id="toc-discussion-and-policy-implications" class="nav-link" data-scroll-target="#discussion-and-policy-implications">Discussion and Policy Implications</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linguistic Exclusion and Health Equity: Indigenous Language as a Barrier to Formal Healthcare in Mexico</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Andrea Perez Pizarro </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>In Mexico, healthcare disparities between Indigenous and non-Indigenous populations are a long-standing public health concern. These disparities are often attributed to systemic barriers, including geographic isolation, poverty, and discrimination in public institutions. However, one of the most persistent and unexplored drivers of healthcare inequality is language. Specifically, the gap between healthcare institutions that operate almost exclusively in Spanish and the millions of individuals who primarily speak one of Mexico’s 68 recognized Indigenous languages. While many studies focus on the ethnic aspect of exclusion, few have analyzed how variation in Spanish proficiency within Indigenous-language speakers affects access to care.</p>
<p>Existing research has shown that Indigenous-language speakers face significant linguistic and cultural barriers in the Mexican healthcare system. For instance, one study found that areas with higher concentrations of Indigenous-language speakers have systematically lower hospital use, even after controlling for income and place of residence <span class="citation" data-cites="garza2025">(<a href="#ref-garza2025" role="doc-biblioref">Garza &amp; Miguel, 2025</a>)</span>. Similarly, when studying Nahuatl-speaking communities in Puebla, it was found that many patients avoid hospitals, not due to cost or distance, but rather because of an inability to communicate with medical staff and a resulting lack of trust in the system <span class="citation" data-cites="haimovich2021">(<a href="#ref-haimovich2021" role="doc-biblioref">Haimovich &amp; Márquez Mora, 2021</a>)</span>. Recent research further revealed that Indigenous-language speakers had significantly lower COVID-19 vaccine uptake, citing fear and negative beliefs rather than access barriers as primary reasons for non-vaccination, despite overall high rates of vaccine availability <span class="citation" data-cites="abascal2024">(<a href="#ref-abascal2024" role="doc-biblioref">Abascal Miguel et al., 2024</a>)</span>.</p>
<p>These studies provide necessary context on the barriers faced by Indigenous communities; however, they typically treat the Indigenous population as internally homogeneous. In reality, there is significant variation in Spanish fluency among speakers of Indigenous languages. Some are bilingual, capable of navigating Spanish-speaking institutions, while others are monolingual, relying exclusively on Indigenous languages in daily life. This linguistic distinction matters. It may explain significant within-group differences in healthcare decisions that broader Indigenous vs.&nbsp;non-Indigenous comparisons overlook.</p>
<p>This project focuses specifically on this understudied divide: the difference in healthcare access between monolingual and bilingual Indigenous-language speakers in Mexico. It uses data from the 2022 results of the nationally representative <em>Encuesta Nacional de Salud y Nutrición (ENSANUT)</em>, or "National Survey of Health and Nutrition" to examine whether individuals who speak only an Indigenous language are more likely to access lower-tier public healthcare services, such as SSA clinics (healthcare facilities operated by Mexico’s Ministry of Health) and IMSS Bienestar (public healthcare program in Mexico that provides free medical services to the uninsured), compared to their bilingual peers.</p>
<p>Although informal care is often assumed to play a significant role in Indigenous healthcare use, the data suggest that this is not the primary driver of observed disparities. Utilization of traditional or alternative providers, such as curanderos, homeopaths, or midwives, is rare within the sample. Instead, the more revealing pattern lies in the type and tier of formal care accessed. While bilingual speakers access a diverse range of services, including pharmacy-affiliated clinics, private hospitals, and employer-based care, monolingual (Indigenous language only) speakers are far more concentrated in basic public facilities that tend to be less administratively complex and more linguistically accessible. These settings may be more geographically proximate and culturally familiar, however, they are also often under-resourced, overburdened, and limited in scope. If monolingual speakers are disproportionately reliant on such facilities, it raises concerns about the equity and effectiveness of healthcare delivery in Indigenous communities.</p>
<p>By narrowing the analysis to Indigenous-language speakers and distinguishing between monolingual and bilingual individuals, this project offers a more precise understanding of how language operates as a structural determinant of healthcare access. It also contributes to policy conversations around linguistic inclusion, suggesting that efforts to close healthcare gaps must go beyond physical access and financial protection to include language accessibility as a central component of equity. In doing so, this study asks not just whether Indigenous people face barriers to care, but which Indigenous people, and why.</p>
</section>
<section id="theory-and-hypothesis" class="level2">
<h2 class="anchored" data-anchor-id="theory-and-hypothesis">Theory and Hypothesis</h2>
<p>Language shapes individuals’ ability to navigate institutional complexity. Access to higher-tier care depends not only on physical availability or insurance coverage, but on the capacity to complete administrative procedures, communicate with providers, and move across institutions. Within Indigenous communities, variation in Spanish proficiency therefore produces systematic differences in healthcare use. Bilingual speakers can access a broader range of providers, while monolingual Indigenous-language speakers face constrained options. By comparing monolingual and bilingual Indigenous-language speakers, the analysis isolates the role of language proficiency while holding ethnicity, income, and location constant.</p>
<blockquote class="blockquote">
<p><strong>Hypothesis</strong>: Among Indigenous-language speakers in Mexico, individuals who do not speak Spanish (monolinguals) are more likely to rely on lower-tier or basic public healthcare services than bilingual speakers, due to the linguistic inaccessibility of more complex care institutions, indicating that language proficiency, beyond ethnic identity, produces meaningful within-group variation in access.</p>
</blockquote>
<p>This hypothesis is both falsifiable and policy-relevant. If monolingual speakers are found to use a narrower and less institutionally diverse range of providers, it would suggest that improving language accessibility should be a central focus in addressing Indigenous health disparities. Policies such as expanded translation services, Indigenous-language outreach, and training of bilingual medical staff would be critical steps toward equitable care.</p>
</section>
<section id="research-design" class="level2">
<h2 class="anchored" data-anchor-id="research-design">Research Design</h2>
<p>The data drawn for this analysis from ENSANUT (2022) was collected by Mexico’s Instituto Nacional de Salud Pública, or "National Institute of Public Health". ENSANUT is a nationally representative cross-sectional survey that uses a probabilistic, stratified sampling design to produce reliable health and demographic estimates at the national, regional, and urban/rural levels. The dataset includes extensive information on healthcare usage, language use, education, household income, and access to insurance, making it suitable for examining how structural factors influence healthcare-seeking behavior <span class="citation" data-cites="ensanut2022">(<a href="#ref-ensanut2022" role="doc-biblioref">ENSANUT 2022</a>)</span>.</p>
<p>Significant data cleaning was required to make the ENSANUT 2022 data analyzable. The raw files were initially formatted using inconsistent semicolon delimiters, which caused structural issues when importing, requiring manual inspection and correction of line breaks, column alignment, and malformed headers. In addition, variable labels were not standardized across files, requiring manual relabeling and synchronization. Once the formatting was corrected, two distinct datasets, one at the individual level and the other at the household level, had to be merged using a unique identifier. This step was further complicated by type mismatches and missing identifiers, which required additional transformations to align variable types and preserve complete observations for analysis. Beyond the research findings, a significant contribution of this project is the creation of a cleaner, more accessible version of ENSANUT 2022 data that can be reused for future analysis and exploration.</p>
<p>The unit of analysis of the ENSANUT is the individual respondent. For this study, the sample is restricted to adults aged 18 and older who report speaking an Indigenous language, using item <strong>H0311</strong> (<em> ¿Habla alguna lengua indígena?/ Do you speak an Indigenous language? </em>). While ENSANUT does not directly ask about ethnic identity, both INSP and Mexico’s national statistics agency (INEGI) routinely use Indigenous language use as an indicator for Indigenous identity in population-level studies <span class="citation" data-cites="villarreal2014ethnic">(<a href="#ref-villarreal2014ethnic" role="doc-biblioref">Villarreal, 2014</a>)</span>. This approach is standard in health equity research and allows for the analysis of intra-group differences within Indigenous populations.</p>
<p>Within this sample, respondents are divided into two groups using item <strong>H0312</strong> (<em>¿Habla también español?/ Do you also speak Spanish? </em>): - Monolinguals: Speak an Indigenous language but not Spanish (H0311 = yes, H0312 = no). - Bilinguals: Speak both an Indigenous language and Spanish (H0311 = yes, H0312 = yes). A binary variable <code>monolingual</code> is created to distinguish these groups, coded as 1 for monolinguals and 0 for bilinguals. This distinction enables testing whether the absence of Spanish proficiency, independent of shared Indigenous identity, affects patterns of healthcare access.</p>
<p>The dependent variable is the type of healthcare institution the respondent usually visits when facing a health need. Item <strong>H0309</strong> asks: <em>“Cuando tiene una necesidad de salud, ¿en dónde se atiende usualmente?/ When you have a health need, where do you usually seek care?" </em>  The responses are grouped into three categories based on institutional complexity and accessibility: - <strong>Tier 1 (High-Complexity Institutional Care)</strong>: IMSS, ISSSTE, PEMEX, Defense, private hospitals. - <strong>Tier 2 (Basic Public Care)</strong>: SSA clinics, IMSS Bienestar, and DIF. - <strong>Tier 3 (Non-Institutional/Alternative Care)</strong>: pharmacy consults, home-based care, traditional healers, homeopaths.</p>
<p>Tier 1 institutions represent the most complex, well-resourced, and bureaucratically integrated parts of Mexico’s healthcare system, offering specialized care and requiring formal employment or affiliation for access <span class="citation" data-cites="who2020">(<a href="#ref-who2020" role="doc-biblioref">World Health Organization, 2020</a>)</span>. Tier 2 includes publicly funded services which are designed for the uninsured, and focus on basic care delivery in marginalized or rural communities <span class="citation" data-cites="trade2023">(<a href="#ref-trade2023" role="doc-biblioref">International Trade Administration, 2023</a>)</span>. Tier 3 encompasses informal and non-institutional options that are often sought due to cultural preferences, affordability, or limited trust in formal providers <span class="citation" data-cites="who2020">(<a href="#ref-who2020" role="doc-biblioref">World Health Organization, 2020</a>)</span>. This categorization is consistent with established public health literature on Mexico’s healthcare segmentation, allowing for a consistent analysis.</p>
<p>For the purposes of hypothesis testing, a binary variable tier2care is constructed: 1 if the respondent uses Tier 2 care, 0 if they use any other tier. Tier 2 institutions are the most accessible segment of the formal healthcare system for uninsured and marginalized populations, unlike Tier 1 institutions, which require formal employment or institutional affiliation. Tier 2 services are publicly funded, universally available, and often serve as the default option in rural or low-resource settings. They also tend to have fewer bureaucratic requirements, making them more navigable for individuals with limited Spanish proficiency, low literacy, or unfamiliarity with state institutions. By focusing on Tier 2 care, this analysis identifies a critical point at which monolingual Indigenous-language speakers may retain access to institutional services but are more likely to be diverted from higher-complexity Tier 1 care due to structural and linguistic barriers. This tier serves as a formal yet accessible middle ground, allowing the analysis to test whether language proficiency affects reliance on this level of care.</p>
<p>To reduce omitted variable bias, the model includes the following control variables: - <strong>Education level (H0317A)</strong>: Ordinal variable capturing the highest grade completed (no schooling to university). - <strong>Income bracket</strong>: Derived from ENSANUT’s household income sections (I and VI), capturing relative socioeconomic status. - <strong>Insurance status (H0310A)</strong>: Whether the respondent has formal healthcare coverage through IMSS, ISSSTE, or other systems. - <strong>Urban/rural residence</strong>: Binary variable indicating household location type. These controls account for structural drivers of healthcare access, such as affordability, geographic proximity, and institutional affiliation, that could confound the relationship between language ability and healthcare-seeking behavior.</p>
</section>
<section id="summary-statistics" class="level1">
<h1>Summary Statistics</h1>
<div class="cell">
<div class="cell-output-display">
<div id="pnmydgxysx" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#pnmydgxysx table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#pnmydgxysx thead, #pnmydgxysx tbody, #pnmydgxysx tfoot, #pnmydgxysx tr, #pnmydgxysx td, #pnmydgxysx th {
  border-style: none;
}

#pnmydgxysx p {
  margin: 0;
  padding: 0;
}

#pnmydgxysx .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#pnmydgxysx .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#pnmydgxysx .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#pnmydgxysx .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#pnmydgxysx .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pnmydgxysx .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pnmydgxysx .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#pnmydgxysx .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#pnmydgxysx .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#pnmydgxysx .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#pnmydgxysx .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#pnmydgxysx .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#pnmydgxysx .gt_spanner_row {
  border-bottom-style: hidden;
}

#pnmydgxysx .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#pnmydgxysx .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#pnmydgxysx .gt_from_md > :first-child {
  margin-top: 0;
}

#pnmydgxysx .gt_from_md > :last-child {
  margin-bottom: 0;
}

#pnmydgxysx .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#pnmydgxysx .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#pnmydgxysx .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#pnmydgxysx .gt_row_group_first td {
  border-top-width: 2px;
}

#pnmydgxysx .gt_row_group_first th {
  border-top-width: 2px;
}

#pnmydgxysx .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pnmydgxysx .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#pnmydgxysx .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#pnmydgxysx .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pnmydgxysx .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#pnmydgxysx .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#pnmydgxysx .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#pnmydgxysx .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#pnmydgxysx .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#pnmydgxysx .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pnmydgxysx .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pnmydgxysx .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#pnmydgxysx .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#pnmydgxysx .gt_left {
  text-align: left;
}

#pnmydgxysx .gt_center {
  text-align: center;
}

#pnmydgxysx .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#pnmydgxysx .gt_font_normal {
  font-weight: normal;
}

#pnmydgxysx .gt_font_bold {
  font-weight: bold;
}

#pnmydgxysx .gt_font_italic {
  font-style: italic;
}

#pnmydgxysx .gt_super {
  font-size: 65%;
}

#pnmydgxysx .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#pnmydgxysx .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#pnmydgxysx .gt_indent_1 {
  text-indent: 5px;
}

#pnmydgxysx .gt_indent_2 {
  text-indent: 10px;
}

#pnmydgxysx .gt_indent_3 {
  text-indent: 15px;
}

#pnmydgxysx .gt_indent_4 {
  text-indent: 20px;
}

#pnmydgxysx .gt_indent_5 {
  text-indent: 25px;
}

#pnmydgxysx .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#pnmydgxysx div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<thead>
<tr class="header gt_heading">
<th colspan="5" class="gt_heading gt_title gt_font_normal gt_bottom_border">Table 1. Summary Statistics of Key Variables</th>
</tr>
<tr class="odd gt_col_headings">
<th id="Variable" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Variable</th>
<th id="Mean" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Mean</th>
<th id="SD" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">SD</th>
<th id="Min" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Min</th>
<th id="Max" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Max</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">monolingual</td>
<td class="gt_row gt_right" headers="Mean">0.01</td>
<td class="gt_row gt_right" headers="SD">0.08</td>
<td class="gt_row gt_right" headers="Min">0.00</td>
<td class="gt_row gt_right" headers="Max">1.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">tier2care</td>
<td class="gt_row gt_right" headers="Mean">0.45</td>
<td class="gt_row gt_right" headers="SD">0.50</td>
<td class="gt_row gt_right" headers="Min">0.00</td>
<td class="gt_row gt_right" headers="Max">1.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">escolaridad</td>
<td class="gt_row gt_right" headers="Mean">3.69</td>
<td class="gt_row gt_right" headers="SD">2.79</td>
<td class="gt_row gt_right" headers="Min">0.00</td>
<td class="gt_row gt_right" headers="Max">12.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">ingreso</td>
<td class="gt_row gt_right" headers="Mean">2.29</td>
<td class="gt_row gt_right" headers="SD">1.79</td>
<td class="gt_row gt_right" headers="Min">1.00</td>
<td class="gt_row gt_right" headers="Max">9.00</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Variable">derechohabiencia</td>
<td class="gt_row gt_right" headers="Mean">0.47</td>
<td class="gt_row gt_right" headers="SD">0.50</td>
<td class="gt_row gt_right" headers="Min">0.00</td>
<td class="gt_row gt_right" headers="Max">1.00</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Variable">area</td>
<td class="gt_row gt_right" headers="Mean">0.24</td>
<td class="gt_row gt_right" headers="SD">0.43</td>
<td class="gt_row gt_right" headers="Min">0.00</td>
<td class="gt_row gt_right" headers="Max">1.00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Table 1 presents summary statistics for key variables used in the analysis. The proportion of monolingual Indigenous-language speakers is relatively low (1%), consistent with national estimates, but analytically significant due to its heightened vulnerability. Approximately 45% of respondents use Tier 2 care, making it the most common care pathway in the sample. The average education level (escolaridad) is 3.7 years, indicating low formal schooling, and ingreso (income decile) centers around the lower third of the distribution. Nearly half of respondents report derechohabiencia (health insurance coverage), and about one-quarter live in rural areas (area = 1).</p>
<p>The main model is a logistic regression estimating the probability of Tier 2 care usage:</p>
<p><span class="math display">\[
\text{logit}(\text{Pr}(\text{Tier2Care}_i = 1)) = \beta_0 + \beta_1 \cdot \text{Monolingual}_i + \beta_2 \cdot \text{Escolaridad}_i + \beta_3 \cdot \text{Ingreso}_i + \beta_4 \cdot \text{Derechohabiencia}_i + \beta_5 \cdot \text{Area}_i + \epsilon_i
\]</span></p>
<section id="empirical-extension" class="level3">
<h3 class="anchored" data-anchor-id="empirical-extension">Empirical Extension</h3>
<p>To test the robustness of the relationship between language proficiency and healthcare access, an empirical extension that controls for state-level variation in healthcare availability and demographic composition is conducted. Specifically, respondents from Oaxaca, the state with the highest proportion of Indigenous-language speakers, are compared to a pooled group of three states: Mexico City (CDMX), Jalisco, and Nuevo León, which are among the least Indigenous and most economically developed in the country. This design enables the assessment of whether the observed relationship between monolingualism and Tier 2 care persists even when accounting for regional differences in healthcare infrastructure and demographic context.</p>
<p>According to INEGI, over 30% of Oaxaca’s population speaks an Indigenous language, making it a focal point for understanding linguistic access barriers in public services. In contrast, the comparison states represent more urbanized and better-resourced settings, with less than 1% of the population speaking an Indigenous language <span class="citation" data-cites="inegi2022pueblos">(<a href="#ref-inegi2022pueblos" role="doc-biblioref">INEGI, 2022</a>)</span>. By holding the analytic framework constant while changing the geographic context, this extension tests whether the monolingual–bilingual gap in Tier 2 care use is context-sensitive or a generalizable pattern. If the association between monolingualism and greater reliance on Tier 2 care remains strong in Oaxaca but diminishes or disappears in the pooled states, it would suggest that linguistic exclusion interacts with local service structures. On the other hand, if the pattern holds across both contexts, it reinforces the argument that language proficiency alone, independent of geography, systematically conditions access to institutional care. In either case, this extension offers deeper insight into the mechanisms of health inequity in Mexico and underscores the need for linguistically responsive public health policies in both high- and low-Indigenous-density regions.</p>
</section>
<section id="findings" class="level3">
<h3 class="anchored" data-anchor-id="findings">Findings</h3>
<p>To visually explore how healthcare-seeking behavior differs by language proficiency, Figure 1 plots the distribution of respondents’ usual healthcare sources by language group.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/top-care-barplot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><em>Figure 1.</em> Usual Healthcare Source by Language Group (ENSANUT 2022). This figure shows the proportion of respondents who report each type of healthcare facility as their usual source of care by language group (monolingual, bilingual, and not reported). Monolingual Indigenous-language speakers overwhelmingly report using SSA clinics, with over 60% relying on this Tier 2 service. Their use of IMSS, a Tier 1 institution, is significantly lower than that of bilingual speakers. Additionally, monolingual speakers show limited reliance on private hospitals or alternative options like pharmacy clinics and home visits. These patterns support the hypothesis that language proficiency limits the navigation of more complex or bureaucratically demanding institutions.</p>
<p><strong>General Model</strong></p>
<p>To formally test the proposed hypothesis, a logistic regression model using monolingual status and relevant covariates is estimated, with its results being presented in Table 1.</p>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script>

      function styleCell_ryvpq4xs1353rxj6jmql(i, j, css_id) {
          var table = document.getElementById("tinytable_ryvpq4xs1353rxj6jmql");
          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors
          if (cell) {
              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);
              cell.classList.add(css_id);
          } else {
              console.warn(`Cell at (${i}, ${j}) not found.`);
          }
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_ryvpq4xs1353rxj6jmql');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_ryvpq4xs1353rxj6jmql(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_ryvpq4xs1353rxj6jmql");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: 13, j: 1 },  ], css_id: 'tinytable_css_lpvpxhqdnwptnpge6vtj',}, 
          { positions: [ { i: 12, j: 1 },  ], css_id: 'tinytable_css_9o75oxgdi6d4mdlwgy73',}, 
          { positions: [ { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 5, j: 1 }, { i: 6, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 10, j: 1 }, { i: 11, j: 1 },  ], css_id: 'tinytable_css_i68onz4nyhetb5lf6f44',}, 
          { positions: [ { i: 0, j: 1 },  ], css_id: 'tinytable_css_b086ex9kxahsikimwxsf',}, 
          { positions: [ { i: 13, j: 0 },  ], css_id: 'tinytable_css_kd1aws7ks9eoar30ipc5',}, 
          { positions: [ { i: 12, j: 0 },  ], css_id: 'tinytable_css_xzyinp9yetoy8dwxz7ve',}, 
          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 },  ], css_id: 'tinytable_css_38560l61apu5ifeopw4u',}, 
          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_63cxhrjmx2vxru6xtd9u',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  styleCell_ryvpq4xs1353rxj6jmql(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <style>
      /* tinytable css entries after */
      .table td.tinytable_css_lpvpxhqdnwptnpge6vtj, .table th.tinytable_css_lpvpxhqdnwptnpge6vtj { text-align: center; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_9o75oxgdi6d4mdlwgy73, .table th.tinytable_css_9o75oxgdi6d4mdlwgy73 { text-align: center; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_i68onz4nyhetb5lf6f44, .table th.tinytable_css_i68onz4nyhetb5lf6f44 { text-align: center; }
      .table td.tinytable_css_b086ex9kxahsikimwxsf, .table th.tinytable_css_b086ex9kxahsikimwxsf { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_kd1aws7ks9eoar30ipc5, .table th.tinytable_css_kd1aws7ks9eoar30ipc5 { text-align: left; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_xzyinp9yetoy8dwxz7ve, .table th.tinytable_css_xzyinp9yetoy8dwxz7ve { text-align: left; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_38560l61apu5ifeopw4u, .table th.tinytable_css_38560l61apu5ifeopw4u { text-align: left; }
      .table td.tinytable_css_63cxhrjmx2vxru6xtd9u, .table th.tinytable_css_63cxhrjmx2vxru6xtd9u { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
    </style>
    <div class="container">
      <table class="table table-borderless" id="tinytable_ryvpq4xs1353rxj6jmql" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        </thead><caption>Table 1. Logistic Regression: Predicting Use of Tier 2 Care</caption>
              <tbody><tr>
                <th scope="col"> </th>
                <th scope="col">National Model</th>
              </tr>
        
        
        </tbody><tbody>
                <tr>
                  <td>(Intercept)</td>
                  <td>1.385***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.031)</td>
                </tr>
                <tr>
                  <td>monolingual</td>
                  <td>0.777***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.210)</td>
                </tr>
                <tr>
                  <td>escolaridad</td>
                  <td>-0.072***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.005)</td>
                </tr>
                <tr>
                  <td>ingreso</td>
                  <td>-0.094***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.008)</td>
                </tr>
                <tr>
                  <td>derechohabiencia</td>
                  <td>-2.806***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.029)</td>
                </tr>
                <tr>
                  <td>area</td>
                  <td>0.240***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.033)</td>
                </tr>
                <tr>
                  <td>Num.Obs.</td>
                  <td>35085</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<p>The results strongly support the hypothesis that monolingual Indigenous-language speakers are more likely to rely on Tier 2 care. The coefficient on the monolingual variable is 0.777 and statistically significant (p &lt; 0.001), indicating that, holding other factors constant, monolingual individuals have substantially higher odds of using basic public care services such as SSA clinics or IMSS-Bienestar. This finding aligns with the descriptive trends shown earlier and supports the claim that language proficiency is a key determinant of how individuals access the healthcare system.</p>
<p>Other covariates also behave as expected. Education (escolaridad) and income (ingreso) are both negatively associated with Tier 2 care use, suggesting that individuals with higher socioeconomic status are more likely to navigate into higher-tier or private care options. The coefficient on derechohabiencia, which represents having formal health insurance, is strongly negative (-2.806), further confirming that uninsured individuals disproportionately rely on Tier 2 services. The positive effect of area, which flags rural respondents, also aligns with existing literature showing that Tier 2 clinics are the most accessible public health infrastructure in rural zones.</p>
<p>Overall, the model affirms that language remains a significant barrier to institutional navigation, even when controlling for education, income, insurance coverage, and rurality. The magnitude and significance of the monolingual coefficient support the central claim that linguistic exclusion, not just structural poverty, directs individuals into lower-tier care.</p>
<p><strong>Adjusted Model for Region</strong></p>
<p>To assess whether the relationship between language and care tier varies by context, the regression model is adjusted for geographic region, comparing Oaxaca to Jalisco, CDMX, and Nuevo León. Table 2 presents the results of this empirical extension.</p>
<div class="cell">
<div class="cell-output-display">
<!-- preamble start -->

    <script>

      function styleCell_l3uqy9gd60j2ra91blag(i, j, css_id) {
          var table = document.getElementById("tinytable_l3uqy9gd60j2ra91blag");
          var cell = table.rows[i]?.cells[j];  // Safe navigation to avoid errors
          if (cell) {
              console.log(`Styling cell at (${i}, ${j}) with class ${css_id}`);
              cell.classList.add(css_id);
          } else {
              console.warn(`Cell at (${i}, ${j}) not found.`);
          }
      }
      function insertSpanRow(i, colspan, content) {
        var table = document.getElementById('tinytable_l3uqy9gd60j2ra91blag');
        var newRow = table.insertRow(i);
        var newCell = newRow.insertCell(0);
        newCell.setAttribute("colspan", colspan);
        // newCell.innerText = content;
        // this may be unsafe, but innerText does not interpret <br>
        newCell.innerHTML = content;
      }
      function spanCell_l3uqy9gd60j2ra91blag(i, j, rowspan, colspan) {
        var table = document.getElementById("tinytable_l3uqy9gd60j2ra91blag");
        const targetRow = table.rows[i];
        const targetCell = targetRow.cells[j];
        for (let r = 0; r < rowspan; r++) {
          // Only start deleting cells to the right for the first row (r == 0)
          if (r === 0) {
            // Delete cells to the right of the target cell in the first row
            for (let c = colspan - 1; c > 0; c--) {
              if (table.rows[i + r].cells[j + c]) {
                table.rows[i + r].deleteCell(j + c);
              }
            }
          }
          // For rows below the first, delete starting from the target column
          if (r > 0) {
            for (let c = colspan - 1; c >= 0; c--) {
              if (table.rows[i + r] && table.rows[i + r].cells[j]) {
                table.rows[i + r].deleteCell(j);
              }
            }
          }
        }
        // Set rowspan and colspan of the target cell
        targetCell.rowSpan = rowspan;
        targetCell.colSpan = colspan;
      }
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: 17, j: 1 }, { i: 17, j: 2 }, { i: 17, j: 3 },  ], css_id: 'tinytable_css_rkrybk8mickllk10rm5w',}, 
          { positions: [ { i: 12, j: 3 }, { i: 12, j: 1 }, { i: 12, j: 2 },  ], css_id: 'tinytable_css_9ncozbomzf7w7hg5l819',}, 
          { positions: [ { i: 3, j: 1 }, { i: 4, j: 1 }, { i: 1, j: 1 }, { i: 2, j: 1 }, { i: 7, j: 1 }, { i: 8, j: 1 }, { i: 9, j: 1 }, { i: 6, j: 1 }, { i: 11, j: 1 }, { i: 7, j: 2 }, { i: 13, j: 1 }, { i: 14, j: 1 }, { i: 15, j: 1 }, { i: 16, j: 1 }, { i: 7, j: 3 }, { i: 5, j: 1 }, { i: 1, j: 2 }, { i: 2, j: 2 }, { i: 3, j: 2 }, { i: 4, j: 2 }, { i: 10, j: 1 }, { i: 6, j: 2 }, { i: 2, j: 3 }, { i: 8, j: 2 }, { i: 9, j: 2 }, { i: 10, j: 2 }, { i: 11, j: 2 }, { i: 16, j: 2 }, { i: 13, j: 2 }, { i: 14, j: 2 }, { i: 15, j: 2 }, { i: 15, j: 3 }, { i: 3, j: 3 }, { i: 5, j: 2 }, { i: 1, j: 3 }, { i: 6, j: 3 }, { i: 11, j: 3 }, { i: 4, j: 3 }, { i: 5, j: 3 }, { i: 10, j: 3 }, { i: 8, j: 3 }, { i: 9, j: 3 }, { i: 14, j: 3 }, { i: 16, j: 3 }, { i: 13, j: 3 },  ], css_id: 'tinytable_css_nf26vsg7c1fcvpvy1on9',}, 
          { positions: [ { i: 0, j: 1 }, { i: 0, j: 2 }, { i: 0, j: 3 },  ], css_id: 'tinytable_css_t5jbmj6ixd47cchczxp1',}, 
          { positions: [ { i: 17, j: 0 },  ], css_id: 'tinytable_css_vtiu1aw494d9jw07key6',}, 
          { positions: [ { i: 12, j: 0 },  ], css_id: 'tinytable_css_487j5cd9md6qp69cfurc',}, 
          { positions: [ { i: 1, j: 0 }, { i: 2, j: 0 }, { i: 3, j: 0 }, { i: 4, j: 0 }, { i: 5, j: 0 }, { i: 6, j: 0 }, { i: 7, j: 0 }, { i: 8, j: 0 }, { i: 9, j: 0 }, { i: 10, j: 0 }, { i: 11, j: 0 }, { i: 16, j: 0 }, { i: 13, j: 0 }, { i: 14, j: 0 }, { i: 15, j: 0 },  ], css_id: 'tinytable_css_nexp8icamj80mftoayd6',}, 
          { positions: [ { i: 0, j: 0 },  ], css_id: 'tinytable_css_xwkqnw0zvbhmsnewfix2',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  styleCell_l3uqy9gd60j2ra91blag(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <style>
      /* tinytable css entries after */
      .table td.tinytable_css_rkrybk8mickllk10rm5w, .table th.tinytable_css_rkrybk8mickllk10rm5w { text-align: center; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_9ncozbomzf7w7hg5l819, .table th.tinytable_css_9ncozbomzf7w7hg5l819 { text-align: center; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_nf26vsg7c1fcvpvy1on9, .table th.tinytable_css_nf26vsg7c1fcvpvy1on9 { text-align: center; }
      .table td.tinytable_css_t5jbmj6ixd47cchczxp1, .table th.tinytable_css_t5jbmj6ixd47cchczxp1 { text-align: center; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
      .table td.tinytable_css_vtiu1aw494d9jw07key6, .table th.tinytable_css_vtiu1aw494d9jw07key6 { text-align: left; border-bottom: solid #d3d8dc 0.1em; }
      .table td.tinytable_css_487j5cd9md6qp69cfurc, .table th.tinytable_css_487j5cd9md6qp69cfurc { text-align: left; border-bottom: solid black 0.05em; }
      .table td.tinytable_css_nexp8icamj80mftoayd6, .table th.tinytable_css_nexp8icamj80mftoayd6 { text-align: left; }
      .table td.tinytable_css_xwkqnw0zvbhmsnewfix2, .table th.tinytable_css_xwkqnw0zvbhmsnewfix2 { text-align: left; border-top: solid #d3d8dc 0.1em; border-bottom: solid #d3d8dc 0.05em; }
    </style>
    <div class="container">
      <table class="table table-borderless" id="tinytable_l3uqy9gd60j2ra91blag" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        <thead>
        </thead><caption>Table: Effect of Monolingualism on Use of Tier 2 Healthcare</caption>
              <tbody><tr>
                <th scope="col"> </th>
                <th scope="col">National</th>
                <th scope="col">Oaxaca</th>
                <th scope="col">Jalisco, CDMX &amp; Nuevo León</th>
              </tr>
        
        </tbody><tfoot><tr><td colspan="4">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td>(Intercept)</td>
                  <td>1.385***</td>
                  <td>0.668***</td>
                  <td>1.233***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.031)</td>
                  <td>(0.179)</td>
                  <td>(0.080)</td>
                </tr>
                <tr>
                  <td>monolingual</td>
                  <td>0.777***</td>
                  <td>1.278**</td>
                  <td>-11.876</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.210)</td>
                  <td>(0.399)</td>
                  <td>(195.872)</td>
                </tr>
                <tr>
                  <td>escolaridad</td>
                  <td>-0.072***</td>
                  <td>-0.055+</td>
                  <td>-0.082***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.005)</td>
                  <td>(0.030)</td>
                  <td>(0.013)</td>
                </tr>
                <tr>
                  <td>ingreso</td>
                  <td>-0.094***</td>
                  <td>-0.169*</td>
                  <td>-0.099***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.008)</td>
                  <td>(0.068)</td>
                  <td>(0.018)</td>
                </tr>
                <tr>
                  <td>derechohabiencia</td>
                  <td>-2.806***</td>
                  <td>-1.238***</td>
                  <td>-2.835***</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.029)</td>
                  <td>(0.186)</td>
                  <td>(0.073)</td>
                </tr>
                <tr>
                  <td>area</td>
                  <td>0.240***</td>
                  <td>0.246+</td>
                  <td>0.506**</td>
                </tr>
                <tr>
                  <td></td>
                  <td>(0.033)</td>
                  <td>(0.146)</td>
                  <td>(0.180)</td>
                </tr>
                <tr>
                  <td>Num.Obs.</td>
                  <td>35085</td>
                  <td>976</td>
                  <td>5697</td>
                </tr>
                <tr>
                  <td>AIC</td>
                  <td>33549.6</td>
                  <td>1233.5</td>
                  <td>5021.6</td>
                </tr>
                <tr>
                  <td>BIC</td>
                  <td>33600.4</td>
                  <td>1262.8</td>
                  <td>5061.5</td>
                </tr>
                <tr>
                  <td>Log.Lik.</td>
                  <td>-16768.782</td>
                  <td>-610.747</td>
                  <td>-2504.788</td>
                </tr>
                <tr>
                  <td>RMSE</td>
                  <td>0.39</td>
                  <td>0.47</td>
                  <td>0.37</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<p>The results of the regional models reinforce the interpretation that language proficiency meaningfully shapes healthcare access, but this relationship is highly context-dependent. In Oaxaca, the coefficient for monolingual is 1.278 and statistically significant at the 0.01 level. This suggests that in a context where Indigenous languages are more widely spoken, monolingual speakers are still significantly more likely to use Tier 2 public healthcare, even when controlling for income, education, insurance status, and rurality. This finding provides strong support for the hypothesis that linguistic exclusion plays a causal role in structuring access to institutional care, even in regions where Indigenous populations are demographically prominent.</p>
<p>In contrast, the coefficient for monolingual in the pooled Jalisco/CDMX/Nuevo León model is highly unstable and negative (-11.876), but not statistically significant. This is likely due to the extremely low number of monolingual respondents in these states, resulting in high standard errors and unreliable estimates. However, the lack of a meaningful effect in these states, combined with the positive and significant result in Oaxaca, strengthens the argument that language-based healthcare disparities are most visible where monolingual Indigenous individuals are present in sufficient numbers to navigate the system, yet still face structural barriers.</p>
<p>Overall, this geographic comparison shows that the association between language and Tier 2 care use persists across regions and is not driven solely by national averages. It highlights how linguistic exclusion operates differently depending on regional health infrastructure and demographic composition.</p>
</section>
<section id="discussion-and-policy-implications" class="level3">
<h3 class="anchored" data-anchor-id="discussion-and-policy-implications">Discussion and Policy Implications</h3>
<p>This project provides strong evidence that language proficiency is a critical factor shaping access to institutional healthcare among Indigenous-language speakers in Mexico. The national regression model showed that monolingual individuals are significantly more likely to rely on Tier 2 public services, even when controlling for education, income, insurance status, and rurality. This pattern suggests that language acts as a structural filter, guiding monolingual speakers toward lower-complexity providers that are easier to access and navigate. At the same time, it limits their access to higher-tier institutions such as IMSS or ISSSTE. These findings are further supported by the empirical extension, which demonstrated that the effect of monolingualism is both statistically and substantively significant in Oaxaca, the state with the highest density of Indigenous-language speakers. In contrast, the absence of a measurable effect in Jalisco, CDMX, and Nuevo León (states with very few monolingual individuals) highlights the context-specific nature of linguistic exclusion.</p>
<p>The implications of this are clear: public health access in Mexico cannot be meaningfully improved for Indigenous populations without directly addressing the language gap. While Mexico’s health system has made strides toward universal coverage, linguistic inclusion remains an unaddressed barrier to equitable care. Policy efforts should prioritize expanding multilingual services, including the hiring and training of Indigenous-language interpreters, culturally competent healthcare workers, and localized outreach strategies tailored to linguistically isolated communities.</p>
<p>More broadly, this project contributes to health equity research by demonstrating that disparities are not only inter-group (Indigenous vs.&nbsp;non-Indigenous) but also intra-group, particularly when linguistic ability is considered. Future research could strengthen these findings by incorporating qualitative data, such as provider-patient communication breakdowns, or by leveraging longitudinal data to examine how language access influences health outcomes over time. Ultimately, this analysis demonstrates that language is not just a matter of cultural identity, but a key structural determinant of access within Mexico’s healthcare system.</p>
<hr>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-abascal2024" class="csl-entry" role="listitem">
Abascal Miguel, M., Flores, J., &amp; García, R. M. (2024). Language barriers and vaccine uptake: COVID-19 disparities among indigenous language speakers in mexico. <em>PLOS Global Public Health</em>, <em>4</em>(2), e0002921. <a href="https://doi.org/10.1371/journal.pgph.0002921">https://doi.org/10.1371/journal.pgph.0002921</a>
</div>
<div id="ref-garza2025" class="csl-entry" role="listitem">
Garza, M., &amp; Miguel, L. A. (2025). Health disparities among indigenous populations in latin america: A scoping review. <em>International Journal for Equity in Health</em>, <em>24</em>(1), 119. <a href="https://doi.org/10.1186/s12939-025-02495-2">https://doi.org/10.1186/s12939-025-02495-2</a>
</div>
<div id="ref-haimovich2021" class="csl-entry" role="listitem">
Haimovich, P., &amp; Márquez Mora, P. (2021). Language, culture and healthcare: Nahuatl-speaking communities in sierra norte de puebla. <em>Multilingua</em>, <em>40</em>(1), 27–47. <a href="https://doi.org/10.1515/multi-2020-0027">https://doi.org/10.1515/multi-2020-0027</a>
</div>
<div id="ref-inegi2022pueblos" class="csl-entry" role="listitem">
INEGI. (2022). <em>Estadísticas a propósito del día internacional de los pueblos indígenas (comunicado de prensa núm. 430/22)</em>. Instituto Nacional de Estadística y Geografía. <a href="https://www.inegi.org.mx/contenidos/saladeprensa/aproposito/2022/EAP_PueblosInd22.pdf">https://www.inegi.org.mx/contenidos/saladeprensa/aproposito/2022/EAP_PueblosInd22.pdf</a>
</div>
<div id="ref-trade2023" class="csl-entry" role="listitem">
International Trade Administration. (2023). <em>Mexico - healthcare products &amp; services</em>. <a href="https://www.trade.gov/country-commercial-guides/mexico-healthcare-products-services">https://www.trade.gov/country-commercial-guides/mexico-healthcare-products-services</a>
</div>
<div id="ref-villarreal2014ethnic" class="csl-entry" role="listitem">
Villarreal, A. (2014). Ethnic identification and its consequences for measuring inequality in mexico. <em>American Sociological Review</em>, <em>79</em>(4), 775–806. <a href="https://doi.org/10.1177/0003122414541960">https://doi.org/10.1177/0003122414541960</a>
</div>
<div id="ref-who2020" class="csl-entry" role="listitem">
World Health Organization. (2020). <em>Health system review: mexico</em>. WHO Regional Office for Europe. <a href="https://iris.who.int/bitstream/handle/10665/334334/HiT-22-2-2020-eng.pdf">https://iris.who.int/bitstream/handle/10665/334334/HiT-22-2-2020-eng.pdf</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>
